services:
  # Backend API service
  - type: web
    name: cloudshare-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: CLERK_WEBHOOK_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: MAX_FILE_SIZE
        value: 25000000
      - key: UPLOAD_PATH
        value: uploads/
      - key: CLIENT_URL
        fromService:
          name: cloudshare-frontend
          type: web
          property: url

  # Frontend static site
  - type: web
    name: cloudshare-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: cloudshare-api
          type: web
          property: url
      - key: VITE_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: VITE_RAZORPAY_KEY
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
